const title = { id: 'wizard.title', defaultMessage: 'Launch a New Project' };
const titlePreview = { id: 'wizard.title.preview', defaultMessage: 'Your Project Preview' };
const backPreview = { id: 'wizard.back.preview', defaultMessage: 'Back to Edit' };
const step1 = { id: 'wizard.step1', defaultMessage: 'General Information' };
const step2 = { id: 'wizard.step2', defaultMessage: 'Project Zone' };
const step3 = { id: 'wizard.step3', defaultMessage: 'Reforestation Data' };
const step4 = { id: 'wizard.step4', defaultMessage: 'Project Initiation' };
const btnLabel = { id: 'wizard.btn-label', defaultMessage: 'Cancel' };
const DropzoneBtn = { id: 'wizard.drope-zone', defaultMessage: 'Upload image' };
const DropzoneReplace = { id: 'wizard.drope-zone.replace', defaultMessage: 'Replace image' };
const DropzoneDelete = { id: 'wizard.drope-zone.delete', defaultMessage: 'Delete image' };
const step1Input0 = { id: 'wizard.step1.input0', defaultMessage: 'Project Type' };
const step1Input1 = { id: 'wizard.step1.input1', defaultMessage: 'Project Name' };
const step1Input1Place = { id: 'wizard.step1.input1.place', defaultMessage: 'Name' };
const step1Input2 = { id: 'wizard.step1.input2', defaultMessage: 'Project Developer' };
const step1Input2Place = { id: 'wizard.step1.input2.place', defaultMessage: 'Type here' };
const step1Input3 = { id: 'wizard.step1.input3', defaultMessage: 'Duration Of Project' };
const step1Input4 = { id: 'wizard.step1.input4', defaultMessage: 'Project Budget' };
const step1Input4Place = { id: 'wizard.step1.input4.place', defaultMessage: 'USD' };
const step1Input5 = { id: 'wizard.step1.input5', defaultMessage: 'Funders' };
const step1Input5Info = { id: 'wizard.step1.input5.label', defaultMessage: 'Funders Information' };
const step1Input5Place = { id: 'wizard.step1.input5.place', defaultMessage: 'Information' };
const step1Input6 = { id: 'wizard.step1.input6', defaultMessage: 'Project Icon' };
const step1Input7 = { id: 'wizard.step1.input7', defaultMessage: 'Project Description' };
const step1Creator = { id: 'wizard.step1.creator', defaultMessage: 'Add Funder' };
const step1CreatorLabel = { id: 'wizard.step1.creator-label', defaultMessage: 'Funders' };
const prevTitle = { id: 'wizard.step2.prev.title', defaultMessage: 'Let’s set up your reforestation zone!' };
const prevDesc = { id: 'wizard.step2.prev.desc', defaultMessage: 'Outline your area with precision, by either drawing it manually on the map or uploading the GEO data file. Make sure to check the location and borders of your zone once it’s outlined on the map. This will help to avoid overlaps with other reforestation projects’ areas, and incentivise collateral providers and validators to commit to your project.' };

const wizardBtnNext = { id: 'wizard.step1.btn-label.next', defaultMessage: 'Next' };
const wizardBtnBack = { id: 'wizard.step1.btn-label.back', defaultMessage: 'Back' };
const wizardFiles = { id: 'wizard.files', defaultMessage: 'Files' };
const step2Input1 = { id: 'wizard.step2.input1', defaultMessage: 'Map Coordinates' };
const step2GeoLabel = { id: 'wizard.step2.geo', defaultMessage: 'GEOjson File Upload' };
const step2GeoBtn = { id: 'wizard.step2.geo.btn', defaultMessage: 'Upload file' };
const step2BtnReset = { id: 'wizard.step2.geo.reset', defaultMessage: 'Reset' };
const step2BtnLabel = { id: 'wizard.step2.btn-label', defaultMessage: 'Draw Zone' };
const step2Input1Place1 = { id: 'wizard.step2.input1.place1', defaultMessage: 'Longitude' };
const step2Input1Place2 = { id: 'wizard.step2.input1.place2', defaultMessage: 'Latitude' };
const step2Input2 = { id: 'wizard.step2.input2', defaultMessage: 'Region' };
const step2CodePlus = { id: 'wizard.step2.code-plus', defaultMessage: 'Google Plus Code' };
const step2List = { id: 'wizard.step2.list.dwn', defaultMessage: 'Download full coordinates list' };
const step3Input1 = { id: 'wizard.step3.input1', defaultMessage: 'Surface Area, Sq.Km' };
const step3Input2 = { id: 'wizard.step3.input2', defaultMessage: 'Number Of Trees' };
const step3Input3 = { id: 'wizard.step3.input3', defaultMessage: 'Avg Tree Density, Per Sq.Km' };
const step2Types = { id: 'wizard.step2.types', defaultMessage: '.geojson, .kml (files accepted)' };
const step3Input4 = { id: 'wizard.step3.input4', defaultMessage: ' Tree Types' };
const step3Option1 = { id: 'wizard.step3.option1', defaultMessage: 'Coniferous' };
const step3Option2 = { id: 'wizard.step3.option2', defaultMessage: 'Deciduous' };
const step3Option3 = { id: 'wizard.step3.option3', defaultMessage: 'Mixed' };
const step3Ben = { id: 'wizard.step3.ben', defaultMessage: 'Benefits' };
const step3Input5 = { id: 'wizard.step3.input5', defaultMessage: 'Project Documentation"' };
const step3Area = { id: 'wizard.step3.area', defaultMessage: 'Additional Project Information:' };
const step3Public = { id: 'wizard.step3.public', defaultMessage: 'Public' };
const step3Private = { id: 'wizard.step3.private', defaultMessage: 'Private' };
const step3AreaPlace = { id: 'wizard.step3.area.place', defaultMessage: 'Project information' };
const step3TooltipTextArea = { id: 'wizard.step3.tooltip.textarea', defaultMessage: 'The more details you provide about your project, the better it is introduced to the community. Include tree species, suppliers, information about yourself and your team, etc.' };
const step4TitleCoast = { id: 'wizard.step4.title-coast', defaultMessage: 'Project Costs' };
const step4TitleTime = { id: 'wizard.step4.title-time', defaultMessage: 'Project Costs' };
const step4Tooltip1 = { id: 'wizard.step4.tooltip1', defaultMessage: 'The cost of minting the NFT, a unique digital item in the blockchain that will represent the plot of land that will be reforested in your project.' };
const step4Tooltip2 = { id: 'wizard.step4.tooltip2', defaultMessage: 'The amount of DAI to be locked o your wallet to start the project, which can later be used to cover the first stage report upload fee.' };
const step4Tooltip3 = { id: 'wizard.step4.tooltip3', defaultMessage: 'Cost for covering the first stage report upload.' };
const step3TooltipFiles = { id: 'wizard.step3.tooltip.files', defaultMessage: 'Add supporting documentation on your project. Legal documentation on your rights to use the plot of land (i.e. rent agreement, legal ownership, local community permission, etc) will greatly boost your project launch and incentivise collateral providers’ and validators’ support and commitment.' };
const step4Tooltip4 = { id: 'wizard.step4.tooltip4', defaultMessage: 'The total amount to cover your fee for report uploads during all stages of your project.' };
const step4Coast1 = { id: 'wizard.step4.coast1', defaultMessage: 'Project Creation Cost:' };
const step4Coast2 = { id: 'wizard.step4.coast2', defaultMessage: 'Project Deposit:' };
const step4Coast3 = { id: 'wizard.step4.coast3', defaultMessage: 'First Stage Cost:' };
const step4Coast4 = { id: 'wizard.step4.coast4', defaultMessage: 'Total Project Costs:' };
const step4PointDai = { id: 'wizard.step4.point-dai', defaultMessage: ' Data upload fee, USD ' };
const step4PointSlope = { id: 'wizard.step4.point-slope', defaultMessage: 'Data upload fee slope, %' };
const ste4Phase = { id: 'wizard.step4.phase', defaultMessage: 'Phase' };
const step4Preview = { id: 'wizard.step4.preview', defaultMessage: 'Preview' };
const ste4Month = { id: 'wizard.step4.month', defaultMessage: 'Months' };
const previewFiles = { id: 'wizard.preview.files', defaultMessage: 'Uploaded Files' };
const ste4Create = { id: 'wizard.step4.create', defaultMessage: 'Create Project' };
const editTitleCost = { id: 'wizard.edit.cost', defaultMessage: 'Current Project Costs' };
const editLabelBtn = { id: 'wizard.edit.label-btn', defaultMessage: 'Recalculate Project Costs' };
const editBtnUpdt = { id: 'wizard.edit.btn.update', defaultMessage: 'Update Project' };
const wizardPopupTitle = { id: 'wizard.popup.title', defaultMessage: 'Success!' };
const wizardPopupDesc = { id: 'wizard.popup.desc', defaultMessage: 'Congratulations! Your project has been created successfully.' };
const wizardPopupBtn = { id: 'wizard.popup.btn-label', defaultMessage: 'Continue' };
export { title, titlePreview, btnLabel, step1, step2, step3, step4, step1Input0, DropzoneBtn, DropzoneReplace, DropzoneDelete, step2GeoBtn,
  wizardFiles, step1Input1, step1Input1Place, step1Input2, step1Input2Place, step1Input3, step3Option1, step3Option2, step3Option3, previewFiles,
  step1Input4, step1Input4Place, step1Input5, step1Input5Place, step1Input6, step4Tooltip1, step4Tooltip2, step4Tooltip3, step4Tooltip4, step2List,
  step1Input7, step1Creator, step1CreatorLabel, wizardBtnNext, wizardBtnBack, wizardPopupTitle, wizardPopupDesc, wizardPopupBtn, backPreview, editTitleCost,
  step2Input1, step2Input1Place1, step2Input1Place2, step2Input2, step2CodePlus, step2BtnLabel, step4Preview, step1Input5Info, prevTitle, prevDesc, editLabelBtn,
  step3Input1, step3Input2, step3Input3, step2Types, step3Input4, step3Ben, step3Input5, step3Area, step3AreaPlace, step2BtnReset, step3Public, step3Private, editBtnUpdt,
  step4TitleCoast, step4TitleTime, step4Coast1, step4Coast2, step4Coast3, step4Coast4, step4PointDai, step4PointSlope, ste4Phase, ste4Month, step2GeoLabel, ste4Create, step3TooltipTextArea, step3TooltipFiles };
